In [2]:
import yfinance as yf
import pandas as pd
# import matplotlib.pyplot as plt
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_squared_error, r2_score

In [3]:
data = yf.download("NVDA")
data

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open      Volume
Ticker            NVDA        NVDA        NVDA        NVDA        NVDA
Date
1999-01-22    0.037615    0.044779    0.035585    0.040122  2714688000
1999-01-25    0.041556    0.042033    0.037615    0.040600   510480000
1999-01-26    0.038331    0.042869    0.037734    0.042033   343200000
1999-01-27    0.038212    0.039406    0.036301    0.038451   244368000
1999-01-28    0.038092    0.038451    0.037854    0.038212   227520000
...                ...         ...         ...         ...         ...
2025-01-27  118.419998  128.399994  116.699997  124.800003   818830900
2025-01-28  128.990005  129.000000  116.250000  121.809998   579666400
2025-01-29  123.699997  126.889999  120.050003  126.500000   467120600
2025-01-30  124.650002  125.000000  118.099998  123.099998   392925500
2025-01-31  120.070000  127.849998  119.190002  123.779999   388161100

[6548 rows x 5 columns]